/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;

public class AppTest {

  private ArrayList<Process> pl;
  private Context c;

  @Before
  public void initialize() {
    this.pl = new ArrayList<>(Arrays.asList(
        new Process(1, 8, 0),
        new Process(2, 4, 0),
        new Process(3, 2, 0),
        new Process(4, 6, 0),
        new Process(5, 3, 0)));
    this.c = new Context();
  }

  @Test
  public void testFCFSAlgorithm() {
    this.c.setStrategy(new FCFS(this.pl));

    String fcfsGannt = "[(0 - P0 - 5),(5 - P1 - 8), (8 - P2 - 15), (15 - P3 - 16), (16 - P4 - 18)]";
    assertEquals(fcfsGannt, this.c.executeStrat());

  }

  @Test
  public void testSJFAlgorithm() {
    this.c.setStrategy(new SJF(this.pl));

    String fcfsGannt = "[(0 - P0 - 5),(5 - P1 - 8), (8 - P3 - 15), (15 - P4 - 16), (16 - P5 - 18)]";
    assertEquals(fcfsGannt, this.c.executeStrat());

  }

}
