/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class AppTest {

  private List<Process> pl;
  private Context c;

  @Before
  public void initialize() {
    this.pl = new ArrayList<>(Arrays.asList(
        new Process(1, 8, 0),
        new Process(2, 4, 0),
        new Process(3, 2, 0),
        new Process(4, 6, 0),
        new Process(5, 3, 0)));
    this.c = new Context();
  }

  @Test
  public void testFCFSAlgorithm() {
    this.c.setStrategy(new FCFS(this.pl));
    List<Process> values = this.c.executeStrat();
    values.indexOf
    assertEquals("");

  }

  @Test
  public void testSJFAlgorithm() {
    this.c.setStrategy(new SJF(this.pl));
    Map<Integer, ArrayList<Integer>> values = this.c.executeStrat();

    assertEquals("");

  }

  @Test
  public void testSRTFAlgorithm() {
    this.c.setStrategy(new SRTF(pl));
    Map<Integer, ArrayList<Integer>> values = this.c.executeStrat();

    assertEquals("");
  }

}
