/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

public class OperatingSystemsAlgorithmTestcase1 {

  private List<Process> pl;
  private Context c;

  @Before
  public void initialize() {
    this.pl = new ArrayList<>(Arrays.asList(
        new Process(1, 8, 0),
        new Process(2, 4, 0),
        new Process(3, 2, 0),
        new Process(4, 6, 0),
        new Process(5, 3, 0)));
    this.c = new Context();
  }

  @Test
  public void testFCFSAlgorithmCase1() {
    this.c.setStrategy(new FCFS(this.pl));
    List<Process> values = this.c.executeStrat();
    values.sort(Comparator.comparingInt(Process::getID));

    // Process 1: Arrival time = 0, Burst time = 8
    assertEquals(8, values.get(0).getCompletionTime());
    assertEquals(0, values.get(0).getWaitingTime());
    assertEquals(8, values.get(0).getTurnAroundTime());
    // Process 2: Arrival time = 0, Burst time = 4
    assertEquals(12, values.get(1).getCompletionTime());
    assertEquals(8, values.get(1).getWaitingTime());
    assertEquals(12, values.get(1).getTurnAroundTime());
    // Process 3: Arrival time = 0, Burst time = 2
    assertEquals(14, values.get(2).getCompletionTime());
    assertEquals(12, values.get(2).getWaitingTime());
    assertEquals(14, values.get(2).getTurnAroundTime());
    // Process 4: Arrival time = 0, Burst time = 6
    assertEquals(20, values.get(3).getCompletionTime());
    assertEquals(14, values.get(3).getWaitingTime());
    assertEquals(20, values.get(3).getTurnAroundTime());
    // Process 5: Arrival time = 0, Burst time = 3
    assertEquals(23, values.get(4).getCompletionTime());
    assertEquals(20, values.get(4).getWaitingTime());
    assertEquals(23, values.get(4).getTurnAroundTime());
    double[] totalWaitTime = { 0 };
    values.forEach(waitTime -> totalWaitTime[0] += waitTime.getWaitingTime());
    assertEquals(10.8, totalWaitTime[0] / values.size(), 0.0001);
    double[] totalTT = { 0 };
    values.forEach(tTime -> totalTT[0] += tTime.getTurnAroundTime());
    assertEquals(15.4, totalTT[0] / values.size(), 0.0001);
  }

  @Test
  public void testFCFSAlgorithmCase2() {

  }

  @Test
  public void testSJFAlgorithmCase1() {
    this.c.setStrategy(new SJF(this.pl));
    List<Process> values = this.c.executeStrat();
    values.sort(Comparator.comparingInt(Process::getID));
    // Process 1: Arrival time = 0, Burst time = 8
    assertEquals(23, values.get(0).getCompletionTime());
    assertEquals(15, values.get(0).getWaitingTime());
    assertEquals(23, values.get(0).getTurnAroundTime());
    // Process 2: Arrival time = 0, Burst time = 4
    assertEquals(9, values.get(1).getCompletionTime());
    assertEquals(5, values.get(1).getWaitingTime());
    assertEquals(9, values.get(1).getTurnAroundTime());
    // Process 3: Arrival time = 0, Burst time = 2
    assertEquals(2, values.get(2).getCompletionTime());
    assertEquals(0, values.get(2).getWaitingTime());
    assertEquals(2, values.get(2).getTurnAroundTime());
    // Process 4: Arrival time = 0, Burst time = 6
    assertEquals(15, values.get(3).getCompletionTime());
    assertEquals(9, values.get(3).getWaitingTime());
    assertEquals(15, values.get(3).getTurnAroundTime());
    // Process 5: Arrival time = 0, Burst time = 3
    assertEquals(5, values.get(4).getCompletionTime());
    assertEquals(2, values.get(4).getWaitingTime());
    assertEquals(5, values.get(4).getTurnAroundTime());
    double[] totalWaitTime = { 0 };
    values.forEach(waitTime -> totalWaitTime[0] += waitTime.getWaitingTime());
    assertEquals(6.2, totalWaitTime[0] / values.size(), 0.0001);
    double[] totalTT = { 0 };
    values.forEach(tTime -> totalTT[0] += tTime.getTurnAroundTime());
    assertEquals(10.8, totalTT[0] / values.size(), 0.0001);

  }

  @Test
  public void testSRTFAlgorithmCase1() {
    this.c.setStrategy(new SRTF(pl));
    List<Process> values = this.c.executeStrat();
    values.sort(Comparator.comparingInt(Process::getID));
    // Process 1: Arrival time = 0, Burst time = 8
    assertEquals(23, values.get(0).getCompletionTime());
    assertEquals(15, values.get(0).getWaitingTime());
    assertEquals(23, values.get(0).getTurnAroundTime());
    // Process 2: Arrival time = 0, Burst time = 4
    assertEquals(9, values.get(1).getCompletionTime());
    assertEquals(5, values.get(1).getWaitingTime());
    assertEquals(9, values.get(1).getTurnAroundTime());
    // Process 3: Arrival time = 0, Burst time = 2
    assertEquals(2, values.get(2).getCompletionTime());
    assertEquals(0, values.get(2).getWaitingTime());
    assertEquals(2, values.get(2).getTurnAroundTime());
    // Process 4: Arrival time = 0, Burst time = 6
    assertEquals(15, values.get(3).getCompletionTime());
    assertEquals(9, values.get(3).getWaitingTime());
    assertEquals(15, values.get(3).getTurnAroundTime());
    // Process 5: Arrival time = 0, Burst time = 3
    assertEquals(5, values.get(4).getCompletionTime());
    assertEquals(2, values.get(4).getWaitingTime());
    assertEquals(5, values.get(4).getTurnAroundTime());
    double[] totalWaitTime = { 0 };
    values.forEach(waitTime -> totalWaitTime[0] += waitTime.getWaitingTime());
    assertEquals(6.2, totalWaitTime[0] / values.size(), 0.0001);
    double[] totalTT = { 0 };
    values.forEach(tTime -> totalTT[0] += tTime.getTurnAroundTime());
    assertEquals(10.8, totalTT[0] / values.size(), 0.0001);
  }

}
