/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * First Come First Serve CPU scheduling.
 * No preemption
 */
public class FCFS implements Strategy {

  // List containing processes to be scheduled
  private List<Process> processes;

  /**
   * Creates a FCFS scheduler with the given list of processes
   *
   * @param processes the list of processes to schedule
   */
  public FCFS(List<Process> processes) {

    this.processes = processes;

  }

  /**
   * Executes the FCFS scheduling algorithm.
   * Processes are sorted by arrival time and executed sequentially.
   *
   * @return a list of processes with updated completion, turnaround, and waiting times
   */
  @Override
  public List<Process> execute() {

    processes.sort(Comparator.comparingInt(Process::getArrivalTime));

    int currentTime = 0;
    List<Process> finishedProcesses = new ArrayList<>();

    for (Process process : processes) {

      if (currentTime < process.getArrivalTime()) {
        currentTime = process.getArrivalTime();
      }

      // CompletionTime

      int completionTime = currentTime + process.getRemainingBurstTime();
      process.setCompletionTime(completionTime);

      // TurnaroundTime = CompletionTime - ArrivalTime

      int turnAroundTime = completionTime - process.getArrivalTime();
      process.setTurnAroundTime(turnAroundTime);

      // WaitingTime = TurnaroundTime - BurstTime

      int waitingTime = turnAroundTime - process.getRemainingBurstTime();
      process.setWaitingTime(waitingTime);
      finishedProcesses.add(process);

      currentTime = completionTime;
    }

    // AverageWaitingTime

    // AverageTurnaroundTime
    printResults(currentTime);
    return finishedProcesses;

  }

  /**
   * Prints scheduling results including per-process stats and averages.
   *
   * @param time the total time spent executing all processes
   */
  public void printResults(int time) {
    System.out.println("First Come First Serve:\n" +
                      "========================================");

    double averageTurnaroundTime = 0;
    double averageWaitingTime = 0;
    for (Process process : this.processes) {
      averageTurnaroundTime += process.getTurnAroundTime();
      averageWaitingTime += process.getWaitingTime();
      System.out.println(
                          "Process " + process.getID() + " finished\n" +
                          "Completion time = " + process.getCompletionTime() + "\n" +
                          "Turnaround time = " + process.getTurnAroundTime() + "\n" +
                          "Waiting time = " + process.getWaitingTime() + "\n"
                        );
    }
    System.out.println("Average turnaround time = " + averageTurnaroundTime/this.processes.size());
    System.out.println("Average waiting time = " + averageWaitingTime/this.processes.size());
    System.out.println("Total time spent = " + time);
    System.out.println("========================================\n\n");
  }
}
