/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class FCFS implements Strategy {

  private List<Process> processes;

  public FCFS(List<Process> processes) {

    this.processes = processes;

  }

  @Override
  public List<Process> execute() {

    processes.sort(Comparator.comparingInt(Process::getArrivalTime));

    int currentTime = 0;
    List<Process> finishedProcesses = new ArrayList<>();

    for (Process process : processes) {

      if (currentTime < process.getArrivalTime()) {
        currentTime = process.getArrivalTime();
      }

      // CompletionTime

      int completionTime = currentTime + process.getRemainingBurstTime();
      process.setCompletionTime(completionTime);

      // TurnaroundTime = CompletionTime - ArrivalTime

      int turnAroundTime = completionTime - process.getArrivalTime();
      process.setTurnAroundTime(turnAroundTime);

      // WaitingTime = TurnaroundTime - BurstTime

      int waitingTime = turnAroundTime - process.getRemainingBurstTime();
      process.setWaitingTime(waitingTime);
      finishedProcesses.add(process);

      currentTime = completionTime;
    }

    // AverageWaitingTime

    // AverageTurnaroundTime
    return finishedProcesses;

  }
}
