/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ntnu;

public class Main {

  public static void main(String[] args) {

    Context context = new Context();
    context.setStrategy(new FCFS());
    context.executeStrat();

  }
}
